# need super user privileges to execute the following commands
#language: generic
sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA =$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl htts://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-285613
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pchandel09/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pchandel09/docker-react npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master


